name: First-job
on: [push, pull_request]
  branches:
    - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     -  uses: active/checkout@v3
        run: echo "testing"  

